# Generated by Django 2.2.13 on 2020-10-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_auto_20201024_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chosen', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosens', to='webapp.Photo', verbose_name='избр. фотография')),
            ],
            options={
                'verbose_name': 'Избранная фотография',
                'verbose_name_plural': 'Избранные фотографии',
            },
        ),
    ]
