# Generated by Django 2.2.13 on 2020-10-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_chosen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chosen',
            old_name='User',
            new_name='user',
        ),
    ]
